version: '3'

services:
  my-app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/var/www/my-app
    command: tail -f /dev/null
  my-database:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  phpmyadmin:
    image: phpmyadmin
    ports:
      - '1080:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=my-database
      - PMA_USER=root
